Fix delete shoot with invalid credentials
gardener/gardener-extension-provider-azure pull request #588
Opened 2022-10-24 12:43 UTC by elchead

**How to categorize this PR?**

/area control-plane
/kind bug
/platform azure

**What this PR does / why we need it**:
do not err when Azure client is unauthorized in resource group availability check, instead just log the result

**Which issue(s) this PR fixes**:
Fixes https://github.com/gardener/gardener-extension-provider-azure/issues/574

**Special notes for your reviewer**:

**Release note**:

```other operator

```

2022-10-24 12:44 UTC, elchead commented
e2e tested

2022-10-25 07:44 UTC, dkistner reviewed
Looks good to me.
Just a doc string need to be added.

2022-10-25 07:44 UTC, dkistner commented on pkg/azure/client/helper.go
> +func IsAzureAPIUnauthorized(err error) bool {
Could you add a doc string here?

2022-10-26 11:39 UTC, elchead commented
e2e tested:

- creation with invalid credentials + deletion succeeds
- creation with valid credentials (with resource provisioning) + deletion fails:
  - stuck at 59 % because deletion fails due to invalid credentials

2022-11-18 13:06 UTC, kon-angelo commented
/reviewed ok-to-test

2022-11-18 13:07 UTC, kon-angelo commented
/test

2022-11-18 13:14 UTC, ialidzhikov requested changes

2022-11-18 13:14 UTC, ialidzhikov commented on pkg/azure/client/helper.go
> +func IsAzureAPIUnauthorized(err error) bool {
You could add unit tests for the newly introduced func.

2022-11-18 13:14 UTC, ialidzhikov commented on pkg/controller/infrastructure/actuator_delete.go
> +		if azureclient.IsAzureAPIUnauthorized(err) {
Is it possible to add unit tests?

2022-12-02 14:47 UTC, kon-angelo submitted a review, later dismissed
/lgtm

2022-12-02 15:42 UTC, elchead commented
@ialidzhikov could you review my updates please?

2022-12-05 14:24 UTC, ialidzhikov requested changes

2022-12-05 14:24 UTC, ialidzhikov commented on pkg/controller/infrastructure/actuator_delete.go
> +			log.Info("failed to check resource group availability due to invalid credentials", err)
This should be a key value logger, see https://github.com/gardener/gardener-extension-provider-azure/blob/1f43bb5a28d2b67b22517a2cf60853675a20d1cf/vendor/github.com/go-logr/logr/logr.go#L256. 

When there is key without value it should panic with `odd number of arguments passed as key-value pairs for logging`. Can you elaborate how it is working in the current revision?

2022-12-05 14:24 UTC, ialidzhikov commented on pkg/controller/infrastructure/actuator_delete.go
> +			log.Info("failed to check resource group availability due to invalid credentials", err)
According to https://github.com/gardener/gardener/blob/master/docs/development/logging.md, log messages should be capitalized.

2022-12-05 14:24 UTC, ialidzhikov commented on pkg/azure/client/helper.go
> +func IsAzureAPIUnauthorized(err error) bool {
I don't think this comment is applied. Can you check?

2022-12-08 11:00 UTC, kon-angelo approved these changes
/lgtm

2022-12-12 14:17 UTC, kon-angelo commented
@ialidzhikov the latest commit added the tests for the error. Can you PTAL ?

2022-12-14 09:36 UTC, kon-angelo commented
/reviewed ok-to-test

2022-12-14 12:17 UTC, kon-angelo commented
/reviewed ok-to-test

2022-12-14 12:18 UTC, kon-angelo commented
/test

2022-12-14 12:28 UTC, ialidzhikov commented
> @ialidzhikov the latest commit added the tests for the error. Can you PTAL ?

Thanks for applying my suggestions! Please proceed without me.

2022-12-14 13:53 UTC, kon-angelo commented
/test

2022-12-15 11:53 UTC, kon-angelo commented
/test

2022-12-15 12:31 UTC, merged